spring:
  config:
   activate:
    on-profile: prod
  datasource:
   url: jdbc:postgresql://postgres:5432/mobilidade_urbana
   username: ${DB_USER}
   password: ${DB_PASSWORD}
  
  jpa:
   hibernate:
    ddl-auto: validate